# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'The General' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for The General
  pod 'CardIO', '~> 5.4'
  pod 'MagicalRecord', '~> 2.3'
  pod 'FBSDKCoreKit', '~> 4.28'
  pod 'FBSDKLoginKit', '~> 4.28'
  pod 'GoogleSignIn', '~> 4.1'
  pod 'FirebaseAnalytics', '~> 4.0'
  pod 'UrbanAirship-iOS-SDK', '~> 8.6'
  pod 'Nuke', '~> 6.0'  

  # Development Only
  pod 'HockeySDK', '~> 5.0'

  target 'The GeneralTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'The GeneralUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
